#%RAML 1.0 DataType


description: Twitter tweet 
properties:
  conversation_id?: string
  author_id?: string 
  in_reply_to_user_id: string
  language?: string 
  created_at?: datetime
  text: string
  id: string