# Anypoint settings
anypoint:
  platform:
    visualizer:
      layer: Iowa Code Camp System API
      tags: Social Media, System API, Backend

# API and API Manager settings
api:
  protocol: HTTPS
  manager:
    id: '${api.manager.id}'
    flowref: iowacodecamp-socialmedia-sapi-main
twitter: 
  bearer: 
    token: '${twitter.bearer.token}'
iowacodecamp:
  socialmedia: 
    sapi: 
      host: '${iowacodecamp.socialmedia.api.host}'
      port: '${iowacodecamp.socialmedia.sapi.port}'